resolver: lts-8.12
packages:
- '.'
extra-deps:
  - LDAP-0.6.11
flags: {}
extra-package-dbs: []

# docker:
#   enable: true
#   repo: "fpco/stack-build:libldap2"

# image:
#   containers:
#     - base: "fpco/wai-ldap:base"
#       name: "fpco/wai-ldap"
#       executables:
#         - wai-ldap
